export enum QueryKeys {
  USER = "user",
  USERS_PENDING = "users-pending",
  TECHNICIANS = "technicians",
  INSTALLATIONS = "installations",
  RESPONSIBLES = "responsibles",
  PUMPS = "pumps",
  CHECKLISTS = "checklists",
  CHECKLIST = "checklist",
  CHECKLISTS_SUMMARY = "checklists-summary",
  ACTIONS = "actions",
  GROUPS = "groups",
  SUBGROUPS = "subgroups",
  INTERVENTIONS = "interventions",
  INTERVENTION = "intervention",
}
