export enum RouterKeys {
  HOME = "/",
  FORBIDDEN_ACCESS = "/403",
  LOGIN = "/auth",
  MAIN = "/main",
  USERS = "/users",
  UPDATE_PASSWORD = "/update-password",
  USER_REQUIRE_ACTIVATION = "/require-activation-user",
  ANALYTICS = "/analytics",
  SETTINGS = "/settings",
  INSTALLATIONS = "/installations",
  PUMPS = "/pumps",
  INTERVENTIONS = "/interventions",
  NEW_INTERVENTION = "/new-intervention/:id/:installation",
  INTERVENTION = "/intervention/:id",
  CHECKLISTS = "/checklists",
}
