-- FIREPUMP25 — Check-list template tree (CL_GR / CL_SUB_GR / CL_ACTION / CL_ACTION_VALUES)
--
-- Supersedes 20260805_groups_subgroups.sql, which was written before the spec bundle
-- arrived and modelled groups as a GLOBAL catalog. Per the assets they are PER CHECK-LIST:
-- Form1_Groups.xlsx ships groups 1-4 twice, once for each check-list template, with a
-- different PTG name for group 4 in each. A global `unique (code)` cannot hold that.
-- 20260805 was never applied, so there is nothing to migrate off.
--
-- Written by Action#04 (Groups / Sub-Gr Import, SF#081 on PopUp#07), parsing
-- Form1_Groups / Form2_Sub_Groups / Form3_Actions / Form4_Measurements.
-- See docs/data-model.md and docs/spec-inputs.md.
--
-- Design decisions (flagged because they diverge from the spec's literal shape):
--  * Scope column is `checklist_id` -> checklists.id (the real PK, bigint), not the
--    spec's CHECK_LIST:Code. Group/sub-group/action `code` columns keep the spec's
--    per-check-list numbering, so the composite identity is preserved for display and
--    for the INT_RESULT / MEASUREMENTS references that come later.
--  * Structure tables carry the spec's composite natural key as a unique constraint;
--    the _TEXT tables hang off the parent's surrogate id. Faithful identity, simple inserts.
--  * `language` stores the spec's 3-letter key verbatim (PTG / ENG / ENS / ENU / FRA /
--    ESP / GER). Mapping to the app's 2-letter i18n codes happens at read time - ENG/ENS/ENU
--    would all collapse to "en" if we normalised on write.
--  * Text columns are `text`, NOT S(50). The spec says 50; the longest real name in
--    Form1_Groups is 91 characters.
--
-- There is no Supabase CLI linked to this project - run this in the SQL editor.

begin;

-- ---------------------------------------------------------------------------
-- 0. checklists is missing the whole PopUp#07 header block.
--    The form in modules/Interventions/components/NewChecklist.tsx already collects
--    these fields and mapChecklistToRaw writes them, but the table only has
--    (id, nfpa_ed, created_at) - so addChecklist fails with 42703 today, and
--    `nextCode` reads a `code` column that does not exist.
--    Action#04 ends with "Create Record table.CHECK_LIST with data from screen",
--    so these have to exist before the import can attach anything to a check-list.
-- ---------------------------------------------------------------------------
alter table public.checklists
  add column if not exists code integer,
  add column if not exists date text,          -- spec format yyyy.mm.dd, kept as typed
  add column if not exists name text,
  add column if not exists company_resp text,
  add column if not exists name_resp text,
  add column if not exists ph text,
  add column if not exists email text;

-- Backfill Report Nr. for the 6 pre-existing rows, then make it unique.
update public.checklists set code = id where code is null;

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'checklists_code_key') then
    alter table public.checklists add constraint checklists_code_key unique (code);
  end if;
end $$;

-- ---------------------------------------------------------------------------
-- 1. is_admin() - SECURITY DEFINER so the RLS policies below can read
--    profiles.role without depending on the profiles table's own policies.
--    (Carried over from 20260805, which never ran.)
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 1 -- KeyRoles.ADMIN
  );
$$;

-- ---------------------------------------------------------------------------
-- 2. CL_GR  <- Form1_Groups.xlsx  [A CODE | B CHECK-LIST | C GROUP | n x (LANG, NAME)]
-- ---------------------------------------------------------------------------
create table if not exists public.cl_gr (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  checklist_id bigint not null references public.checklists (id) on delete cascade,
  code integer not null,                       -- [C] GROUP
  constraint cl_gr_identity_key unique (checklist_id, code)
);

create table if not exists public.cl_gr_text (
  id bigint generated by default as identity primary key,
  cl_gr_id bigint not null references public.cl_gr (id) on delete cascade,
  language text not null,                      -- PTG / ENG / ...
  text text not null,
  constraint cl_gr_text_key unique (cl_gr_id, language)
);

-- ---------------------------------------------------------------------------
-- 3. CL_SUB_GR  <- Form2_Sub_Groups.xlsx  [.. | C GROUP | D SUB-GROUP | n x (LANG, NAME)]
--    Sub-group names repeat across groups ("Bombas S.I." is 2/1, 3/1 and 4/1),
--    so the name can never be part of the key.
-- ---------------------------------------------------------------------------
create table if not exists public.cl_sub_gr (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  checklist_id bigint not null,
  code_gr integer not null,                    -- [C] GROUP
  code integer not null,                       -- [D] SUB-GROUP
  constraint cl_sub_gr_identity_key unique (checklist_id, code_gr, code),
  constraint cl_sub_gr_parent_fkey foreign key (checklist_id, code_gr)
    references public.cl_gr (checklist_id, code) on update cascade on delete cascade
);

create table if not exists public.cl_subgr_text (
  id bigint generated by default as identity primary key,
  cl_sub_gr_id bigint not null references public.cl_sub_gr (id) on delete cascade,
  language text not null,
  text text not null,
  constraint cl_subgr_text_key unique (cl_sub_gr_id, language)
);

-- ---------------------------------------------------------------------------
-- 4. CL_ACTION  <- Form3_Actions.xlsx
--    [.. | E ACTION | F PERIOD | n x (LANG, TYPE, SOURCE, NAME)]  <- stride 4, not 2
--    `period` is a PERIODICITY code (1 = weekly, 2 = monthly) and is NOT per-language.
--    `pump_type` is CL_ACTION.Pump_Type - open question #9: the spec implies four
--    categories in #Tipos Sub-Grupo NP.xlsx against PUMP_GROUP.Type's three (J/E/D),
--    so it is left as unconstrained text for now.
-- ---------------------------------------------------------------------------
create table if not exists public.cl_action (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  checklist_id bigint not null,
  code_gr integer not null,
  code_sub_gr integer not null,
  code integer not null,                       -- [E] ACTION
  period integer,                              -- [F] PERIOD
  pump_type text,
  constraint cl_action_identity_key unique (checklist_id, code_gr, code_sub_gr, code),
  constraint cl_action_parent_fkey foreign key (checklist_id, code_gr, code_sub_gr)
    references public.cl_sub_gr (checklist_id, code_gr, code) on update cascade on delete cascade
);

-- TYPE and SOURCE vary per language (IPE/PTI; "Instruções do Fabricante"/"Mnfct
-- instructions"), which is why they live here and not on cl_action.
create table if not exists public.cl_action_text (
  id bigint generated by default as identity primary key,
  cl_action_id bigint not null references public.cl_action (id) on delete cascade,
  language text not null,
  type text,                                   -- localized group abbreviation
  source text,                                 -- NFPA-25 clause, or manufacturer instructions
  text text not null,
  constraint cl_action_text_key unique (cl_action_id, language)
);

-- ---------------------------------------------------------------------------
-- 5. CL_ACTION_VALUES  <- Form4_Measurements.xlsx
--    [.. | E ACTION | F INDEX | n x (LANG, NAME)]
--    One row per measurement slot: an action taking RPM after start / 10 min / 15 min
--    gets three. The text is a field LABEL with its unit ("Valor (bar):"), not a value.
-- ---------------------------------------------------------------------------
create table if not exists public.cl_action_values (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  cl_action_id bigint not null references public.cl_action (id) on delete cascade,
  code integer not null,                       -- [F] INDEX
  constraint cl_action_values_key unique (cl_action_id, code)
);

create table if not exists public.cl_values_text (
  id bigint generated by default as identity primary key,
  cl_action_values_id bigint not null references public.cl_action_values (id) on delete cascade,
  language text not null,
  text text not null,
  constraint cl_values_text_key unique (cl_action_values_id, language)
);

-- ---------------------------------------------------------------------------
-- 6. Indexes for the read path (report renders group -> sub-group -> action)
-- ---------------------------------------------------------------------------
create index if not exists cl_gr_checklist_idx        on public.cl_gr (checklist_id, code);
create index if not exists cl_sub_gr_checklist_idx    on public.cl_sub_gr (checklist_id, code_gr, code);
create index if not exists cl_action_checklist_idx    on public.cl_action (checklist_id, code_gr, code_sub_gr, code);
create index if not exists cl_action_values_parent_idx on public.cl_action_values (cl_action_id, code);

-- ---------------------------------------------------------------------------
-- 7. RLS - any signed-in user reads the templates; only the Administrator writes them.
--    Confirmed by #Screens_Pop-ups List.xlsx: PopUp#07 is "Create New Check-List,
--    by Administrator", reached from Screen#03 (Administrator menu). So Action#04 does
--    run as an admin and admin-gated writes are correct here.
-- ---------------------------------------------------------------------------
do $$
declare t text;
begin
  foreach t in array array[
    'cl_gr', 'cl_gr_text', 'cl_sub_gr', 'cl_subgr_text',
    'cl_action', 'cl_action_text', 'cl_action_values', 'cl_values_text'
  ]
  loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists %I on public.%I', t || '_select', t);
    execute format(
      'create policy %I on public.%I for select to authenticated using (true)',
      t || '_select', t);
    execute format('drop policy if exists %I on public.%I', t || '_write', t);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      t || '_write', t);
  end loop;
end $$;

commit;
