-- FIREPUMP25 — Groups / Sub-Groups catalog
--
-- Prerequisite for Action#22 (Update Languages Table / Actions, SF#053) and
-- Action#04 (Groups / Sub-Gr Import, SF#081). See docs/checklist-actions-import.md.
--
-- Design notes:
--  * Names are jsonb keyed by language code ({"en": "...", "pt": "..."}) because the
--    spec's Report_Actions.xlsx carries names "in several languages" and the language
--    list itself is data (Table_Language.xlsx) — a new language must not need a migration.
--  * Tables are keyed on the spec's integer `Code`, so the existing
--    checklistactions.code_group / code_subgroup integers keep working unchanged.
--  * checklistactions deliberately gets NO foreign key to this catalog: those rows are a
--    per-report snapshot and must survive a catalog re-import that drops an action
--    (open question Q3 — replace vs. merge).
--
-- There is no Supabase CLI linked to this project; run this in the SQL editor.

-- ---------------------------------------------------------------------------
-- is_admin(): SECURITY DEFINER so the RLS policies below can check profiles.role
-- without depending on the profiles table's own RLS policies.
-- ---------------------------------------------------------------------------
create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.profiles
    where profiles.id = auth.uid()
      and profiles.role = 1 -- KeyRoles.ADMIN
  );
$$;

-- ---------------------------------------------------------------------------
-- groups
-- ---------------------------------------------------------------------------
create table if not exists public.groups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  code integer not null,
  name jsonb not null default '{}'::jsonb,
  constraint groups_code_key unique (code)
);

-- ---------------------------------------------------------------------------
-- subgroups — code is unique within its group (the "1.1", "1.2" display numbering)
-- ---------------------------------------------------------------------------
create table if not exists public.subgroups (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  code_group integer not null,
  code integer not null,
  name jsonb not null default '{}'::jsonb,
  constraint subgroups_code_group_fkey foreign key (code_group)
    references public.groups (code) on update cascade on delete restrict,
  constraint subgroups_code_key unique (code_group, code)
);

-- ---------------------------------------------------------------------------
-- actions: which group / sub-group a catalog action belongs to.
-- Nullable — existing rows predate the catalog. The composite FK is MATCH SIMPLE,
-- so a half-filled pair (group set, sub-group null) is allowed on purpose while
-- the catalog is being populated.
-- ---------------------------------------------------------------------------
alter table public.actions
  add column if not exists code_group integer,
  add column if not exists code_subgroup integer;

do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'actions_subgroup_fkey'
  ) then
    alter table public.actions
      add constraint actions_subgroup_fkey
      foreign key (code_group, code_subgroup)
      references public.subgroups (code_group, code)
      on update cascade on delete restrict;
  end if;
end $$;

create index if not exists actions_code_group_idx
  on public.actions (code_group, code_subgroup);

-- ---------------------------------------------------------------------------
-- RLS: everyone signed in reads the catalog; only the Administrator writes it
-- (Action#22 / #23 live on Screen#03, the Administrator menu).
-- ---------------------------------------------------------------------------
alter table public.groups enable row level security;
alter table public.subgroups enable row level security;

drop policy if exists groups_select on public.groups;
create policy groups_select on public.groups
  for select to authenticated using (true);

drop policy if exists groups_write on public.groups;
create policy groups_write on public.groups
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop policy if exists subgroups_select on public.subgroups;
create policy subgroups_select on public.subgroups
  for select to authenticated using (true);

drop policy if exists subgroups_write on public.subgroups;
create policy subgroups_write on public.subgroups
  for all to authenticated using (public.is_admin()) with check (public.is_admin());

-- ---------------------------------------------------------------------------
-- Seed the two groups that were until now hardcoded as `checklists.groupTitle`
-- in translations/languages/{en,pt}.ts, so the check-list display does not regress.
-- Real content arrives with Report_Actions.xlsx via Action#22.
-- ---------------------------------------------------------------------------
insert into public.groups (code, name) values
  (1, '{"en": "Pre-Test Inspections", "pt": "Inspeções Pré Ensaio"}'::jsonb),
  (2, '{"en": "Checks and Tests (VE)", "pt": "Verificações e Ensaios (VE)"}'::jsonb)
on conflict (code) do nothing;
